project:
  type: book
  output-dir: docs

book:
  title: "cookbook"
  description: "A personal digital cookbook."
  repo-url: https://github.com/zeshanrajput/cookbook
  repo-actions: [edit, source, issue]
  author: "Zeshan Rajput"
  date: "9/5/2025"
  chapters:
    - index.qmd
    - breakfast.qmd
    - bread.qmd
    - sauces_marinades.qmd
    - main_courses.qmd
    - soups_stews.qmd
    - side_dishes.qmd
    - desserts.qmd
    - drinks.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    sharing: [facebook, twitter, linkedin]
  pdf:
    documentclass: scrreprt



